In [32]:
import tensorflow as tf
import pandas as pd
import numpy as np

In [33]:
df = pd.read_csv('dataset\Biomass_History.csv')

In [34]:
#Check if there are any null values
df.isnull().sum()

Index        0
Latitude     0
Longitude    0
2010         0
2011         0
2012         0
2013         0
2014         0
2015         0
2016         0
2017         0
dtype: int64

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2418 entries, 0 to 2417
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Index      2418 non-null   int16  
 1   Latitude   2418 non-null   float16
 2   Longitude  2418 non-null   float16
 3   2010       2418 non-null   float16
 4   2011       2418 non-null   float16
 5   2012       2418 non-null   float16
 6   2013       2418 non-null   float16
 7   2014       2418 non-null   float16
 8   2015       2418 non-null   float16
 9   2016       2418 non-null   float16
 10  2017       2418 non-null   float16
dtypes: float16(10), int16(1)
memory usage: 52.1 KB


In [36]:
# df.head()
df.loc[:]['Longitude'][0]

71.33144

In [40]:
#converting float64 to float32 and int64 to int16
columns = list(df.columns)
for column in columns:
    if(type(df[column][0]) == np.float64):
        df[column] = df[column].astype('float16')
    if(type(df[column][0]) == np.int64):
        df[column] = df[column].astype('int16')
        

In [39]:
df.head()

Index   Latitude  Longitude       2010       2011       2012       2013  \
0      0  24.671875    71.3125   8.476562   8.867188   9.203125   6.023438   
1      1  24.671875    71.4375  24.031250  28.546875  25.859375  21.640625   
2      2  24.671875    71.5000  44.843750  66.125000  56.968750  53.000000   
3      3  24.671875    71.5625  59.968750  80.812500  78.937500  63.156250   
4      4  24.671875    71.6250  14.656250  19.328125  21.921875  17.906250   

        2014       2015       2016        2017  
0  10.789062   6.648438   7.386719    5.179688  
1  34.406250  27.359375  40.437500   42.125000  
2  70.937500  42.531250  59.187500   73.187500  
3  93.500000  70.187500  74.562500  101.062500  
4  19.531250  19.171875  16.531250   26.093750

In [55]:
#Scaling the columns from 2010 to 2017
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
ct = ColumnTransformer([('std',StandardScaler(),[str(x) for x in np.arange(2010,2018)]),
                       ],remainder='passthrough')

In [56]:
transformed_df = ct.fit_transform(df)

In [61]:
transformed_df= pd.DataFrame(transformed_df,columns=['2010','2011','2012','2013' ,'2014','2015','2016','2017','Index','Latitude','Longitude'])

In [64]:
transformed_df = transformed_df[columns]

In [68]:
ct.named_transformers_['std'].scale_

array([146.47385971, 142.23753878, 110.22873111, 180.29937463,
       139.84241837, 129.66308795, 102.06902213, 158.95757538])

In [74]:
ct.named_transformers_['std'].mean_

array([144.4008336 , 150.86157622, 109.47009888, 161.88708901,
       157.95429989, 132.89863903, 113.08784782, 159.16175424])

In [75]:
ct.named_transformers_['std'].var_

array([21454.59157898, 20231.51743886, 12150.37316137, 32507.86449169,
       19555.90197633, 16812.51637615, 10418.08527856, 25267.5107711 ])

In [69]:
#cross validation

In [70]:
df['2010']

0        8.476562
1       24.031250
2       44.843750
3       59.968750
4       14.656250
          ...    
2413     5.199219
2414     0.122314
2415     0.039429
2416     2.718750
2417     0.621094
Name: 2010, Length: 2418, dtype: float16

In [76]:
(df['2010'] -144.4008336)/np.sqrt(21454.5915789)

0      -0.927246
1      -0.821777
2      -0.679199
3      -0.576172
4      -0.885742
          ...   
2413   -0.949707
2414   -0.984863
2415   -0.985352
2416   -0.966797
2417   -0.981445
Name: 2010, Length: 2418, dtype: float16

In [78]:
transformed_df['2010']

0      -0.927734
1      -0.821777
2      -0.679688
3      -0.576660
4      -0.885742
          ...   
2413   -0.950684
2414   -0.984863
2415   -0.985840
2416   -0.966797
2417   -0.981445
Name: 2010, Length: 2418, dtype: float32